# backend/Dockerfile
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY server/package*.json ./
RUN npm install

# Copy source code
COPY server/. .

# Expose backend port
EXPOSE 5000

# Start the server
CMD ["npm", "start"]
