# Use Node.js LTS version
FROM node:18-alpine

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY client/package*.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY client/. .

# Expose port 3000 (React dev server)
EXPOSE 3000

# Start React app
CMD ["npm", "start"]
