- hosts: localhost
  connection: local
  vars:
    dockerhub_username: "{{ lookup('env','DOCKER_USER') }}"
    dockerhub_password: "{{ lookup('env','DOCKER_PASS') }}"

  tasks:
    - name: Docker login
      community.docker.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Pull server Docker image
      community.docker.docker_image:
        name: binuriweerasinghe/devops_project-server:latest
        source: pull

    - name: Pull client Docker image
      community.docker.docker_image:
        name: binuriweerasinghe/devops_project-client:latest
        source: pull

    - name: Stop old containers
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - devops_project-server
        - devops_project-client
        - mongo

    - name: Run MongoDB container
      community.docker.docker_container:
        name: mongo
        image: mongo:6.0
        ports:
          - "27018:27017"
        volumes:
          - "{{ lookup('env','WORKSPACE') }}/mongo-data:/data/db"
        restart_policy: unless-stopped

    - name: Run server container
      community.docker.docker_container:
        name: devops_project-server
        image: binuriweerasinghe/devops_project-server:latest
        ports:
          - "5000:5000"
        env_file: "{{ lookup('env','WORKSPACE') }}/server/.env"
        restart_policy: unless-stopped

    - name: Run client container
      community.docker.docker_container:
        name: devops_project-client
        image: binuriweerasinghe/devops_project-client:latest
        ports:
          - "3000:3000"
        env_file: "{{ lookup('env','WORKSPACE') }}/client/.env"
        restart_policy: unless-stopped
